name:                backprop
version:             0.2.6.1
github:              mstksg/backprop
homepage:            https://backprop.jle.im
license:             BSD3
author:              Justin Le
maintainer:          justin@jle.im
copyright:           (c) Justin Le 2018
tested-with:         GHC >= 8.0

extra-source-files:
- README.md
- CHANGELOG.md
- Build.hs
- samples/*.lhs
- renders/*.pdf
- renders/*.md
- doc/*

# Metadata used when publishing your package
synopsis:            Heterogeneous automatic differentation
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: |
    Write your functions to compute your result, and the library will
    automatically generate functions to compute your gradient.

    Implements heterogeneous reverse-mode automatic differentiation, commonly
    known as "backpropagation".

    See <https://backprop.jle.im> for official introduction and documentation.

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wredundant-constraints
# - -Werror

dependencies:
- base >=4.7 && <5
- deepseq
- microlens
- vector

library:
  source-dirs: src
  exposed-modules:
  - Numeric.Backprop
  - Numeric.Backprop.Class
  - Numeric.Backprop.Explicit
  - Numeric.Backprop.Num
  - Numeric.Backprop.Op
  - Prelude.Backprop
  - Prelude.Backprop.Explicit
  - Prelude.Backprop.Num
  other-modules:
  - Numeric.Backprop.Internal
  - Data.Type.Util
  dependencies:
  - containers
  - primitive
  - reflection
  - transformers
  - vinyl >= 0.9.1

benchmarks:
  backprop-mnist-bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - backprop
    - criterion
    - directory
    - hmatrix >=0.18
    - microlens-th
    - mwc-random
    - time
